# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-09 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(max_length=16384)),
                ('pid', models.IntegerField(default=0)),
                ('uid', models.IntegerField()),
                ('gid', models.IntegerField()),
            ],
        ),
    ]
