# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-09 02:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pubtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
