# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-08 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('gender', models.IntegerField(default=1)),
                ('age', models.IntegerField(default=0)),
                ('phone', models.CharField(max_length=11)),
            ],
        ),
    ]
