# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-09 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('year', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('author', models.CharField(max_length=11)),
            ],
        ),
    ]
