#!/bin/bash
dst="10.1.1.1"
port="30000"
user="-- czl --"
if [ -z "$1" ];then
    while read line
    do
        if [ -n "$line" ];then
            echo "${user}: $line" | nc $dst $port
        fi
    done
else
    echo "${user}: $@" | nc $dst $port
fi

exit 0
