# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-09 06:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='father',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='store.Father'),
        ),
    ]
